### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Patrikgrinsvall** [JezuzStardust/blender-svg-parser#4]
I would like so much to get this to work and to contribute to this repo. 

But, i cant get the example to work and i dont want to copy paste code into a new addon but rather do it as a pr. 
What version of blender are you using? I have tested with 2.93.4 on ubuntu installed as a snap and 3-alpha downloaded.

I get 
```
File "/home/user/svg-parser/untitled.blend/Text", line 3, in <module>
ModuleNotFoundError: No module named 'svgparser
```
error even i have script path set correct. I have also tried to move around blend file and svgparser directory in many different places on the disk but still same error. 

I had another error first but that was resolved by deleting `~/.config/blender` i think it was

Here is the script i'm trying to run. Did i miss anything obvious?
```
import bpy
import svgparser 
ld = svgparser.svgparser.SVGLoader(bpy.context, "/home/user/Documents/KOD/blender_svg/svg/apple.svg")
ld.parse()
ld.create_blender_splines()
```

I also tried to add the directory to python path from inside directory of my own script without any luck:
```
import sys
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.dirname(SCRIPT_DIR))
```

**Comment by JezuzStardust** [comment]
I think that I was a bit unclear about how to correctly set the path. Here are the full steps. 

1. Create a folder somewhere, I will call it "scripts" for this explanation. 
2. Within "scripts", create empty folders called exactly: "addons", "modules", and "startup". 
3. Clone the project into "modules" 

The final structure of the folder should be: 
```
scripts
   addons 
   modules
      svgparser
   startup
```
Then set the script path to the full path of Base. Blender is a bit quirky with this, but in case this works for you, I will update the instructions so that this is clearer in the future. 

On [this Blender manual page](https://docs.blender.org/manual/en/latest/editors/preferences/file_paths.html) you can find information about this. It says: "You will need to create specific subfolders in this path which match the structure of the scripts folder found in Blender’s installation directory.". My installation has a few other subfolders to "scripts", however, in my experience it is enough to include these three. Probably it works if you only have the subfolder "modules" and put the project files there. But I have not tested this. 

Thank you for notifying me about this, and please let me know how it goes!

I am really happy to see people actually wanting to use this code! I did not expect that!

After about a hundred edits of this answer: I currently use **Blender 2.93.5**, but this has worked ok for at least the last four, five versions. I always update to the latest version.
